### ISSUE TITLE
Опечатка в 5.2.2

### ISSUE THREAD

**Issue by Onotole1** [netology-code/and-homeworks#44]
https://github.com/netology-code/and-homeworks/blob/master/5.2.Internal/5.2.2/README.md

В тексте:

> Возьмите домашнюю работу "Сохранение/восстановление текста во внутренний файл 5.1.1 и добавьте туда CheckBox "Хранить логин во внешнем хранилище". 

Ссылка на задачу 5.2.1 правильная, но номер задачи должен быть 5.2.1, а не 5.1.1

ОР:
> Возьмите домашнюю работу "Сохранение/восстановление текста во внутренний файл 5.2.1 и добавьте туда CheckBox "Хранить логин во внешнем хранилище".

**Comment by ikrieg** [comment]
Спасибо, исправили
